# Generated by Django 3.1.7 on 2021-03-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210313_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
