# Generated by Django 3.1.7 on 2021-03-13 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210313_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.group'),
        ),
    ]
