# Generated by Django 3.1.7 on 2021-03-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210313_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='content',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='content',
            new_name='name',
        ),
    ]
