# Generated by Django 3.1.7 on 2021-03-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=models.TextField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
