# Generated by Django 3.1.7 on 2021-03-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210314_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='snippet',
            constraint=models.UniqueConstraint(fields=('body', 'user_id'), name='unique_snippetbody_per_user'),
        ),
    ]
